name: Auto-merge Dependency PRs

on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-automerge:
    if: >-
      github.actor == 'dependabot[bot]' ||
      contains(github.event.pull_request.labels.*.name, 'dependencies') ||
      contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Dependabot metadata
        id: meta
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash

      - name: Auto-merge when ready
        uses: peter-evans/auto-merge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          delete-branch: true

