name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Lint
        run: |
          python -m flake8 src tests

      - name: Test
        run: |
          python -m pytest -q

      - name: Generate sample reports
        run: |
          mkdir -p reports
          python src/cloudguard/cli.py --provider aws \
            --input sample_data/aws/s3_buckets.json \
            --report html --out reports/sample_s3.html || true
          python src/cloudguard/cli.py --provider aws \
            --input sample_data/aws/iam_policies.json \
            --report html --out reports/sample_iam.html || true

      - name: Upload report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cloudguard-reports
          path: reports/
