name: Docker
on:
  push:
    tags: ['v*']
permissions:
  contents: read
  packages: write
jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: cloudguard
      VERSION: ${{ github.ref_name }}
      OWNER: ${{ github.repository_owner }}
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build image
        run: |
          OWNER_LC=$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')
          IMAGE="ghcr.io/${OWNER_LC}/${IMAGE_NAME}"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -t "$IMAGE:latest" -t "$IMAGE:$VERSION" .
      - name: Push
        run: |
          docker push "$IMAGE:$VERSION"
          docker push "$IMAGE:latest"
