name: Conventional PR Title

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions: {}

jobs:
  lint-title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        run: |
          TITLE='${{ github.event.pull_request.title }}'
          echo "PR title: $TITLE"
          if echo "$TITLE" | grep -Eq '^(feat|fix|chore|docs|refactor|test|build|ci|perf|style)(\(.*\))?: .+'; then
            echo "Title is conventional."
          else
            echo "Invalid PR title. Use Conventional Commits, e.g., 'fix: short summary'" >&2
            exit 1
          fi
